sudo: required
language: python
services:
  - docker

cache: ccache

env:
    matrix:
      - OS=centos DIST=7
      - OS=fedora DIST=23
      - OS=fedora DIST=24
      - OS=ubuntu DIST=xenial
      - OS=ubuntu DIST=yakkety
      - OS=debian DIST=stretch

script: curl -L http://packpack.github.io/travis.sh | sh
